title: TITLE
email: toyoshim@gmail.com
description: >
  Hoge!
baseurl: "/gh-sandbox"
url: "https://toyoshim.github.io"
twitter_username: jekyllrb
github_username:  jekyll
markdown: kramdown
remote_theme: toyoshim/midnight@nav
